WIP: Migrate server to use database
Updated user, login, and passwd routes

Updated client init script and messenger

Add db.py for database operations/pool management

Add 001_users.sql migration to create user tables

Clean up / improve most python import modules

Add migrate.py to run db schema migrations on install/update

Add dev-install.py and dev/devserver scripts to run local dev server

Add support for --help/--version in user-facing commands

diff --git a/static/client/functions/messenger b/static/client/functions/messenger
--- a/static/client/functions/messenger
+++ b/static/client/functions/messenger
@@ -4,72 +4,129 @@
 ## Provides functions to interact with server
 ##
 ## Functions:
+##   __gs_logged_in
+##     helper function that returns 0 if user is logged in
+##   __gs_api_key ACTION [OPTS]
+##     supported ACTION values and their OPTS:
+##       save KEY: sets raw API key in env and saves to local file for future logins
+##                 returns non-zero if unable to save key to local GS_AUTH_FILE
+##       remove: unsets GS_API_KEY and GS_USER_STATE from env and removes GS_AUTH_FILE
 ##   __gs_json_content [KEY VAL [KEY VAL [...]]]
-##     function that formats input keys/vals as a json string
-##     calling with KEY1 VAL1 KEY2 VAL2 prints '"KEY1": "VAL1", "KEY2": "VAL2"'
+##     function that formats simple input keys/vals as a json string
+##     calling with KEY1 VAL1 KEY2 VAL2 prints '{"KEY1":"VAL1","KEY2":"VAL2"}'
+##     simple json output is nestable with VAL=$(__gs_json_content [KEY VAL [...]])
 ##   __gs_curl_post ROUTE [KEY VAL [KEY VAL [...]]]
-##     function that curls server with POST request to URL/ROUTE
+##     function that curls server with POST request to GS_URL/ROUTE
 ##     uses KEY/VAL pairs entered to call __gs_json_content and adds result to msg
-##     by default adds user/key/ver to every message
-##     this function is the preferred way to interact with the server
+##     by default adds user/curuser/host/key/ver to every message
+##     this function is the default way to interact with the server api
+##     prints server response after checking for old api version or key
 ##   __gs_parse_response JQCODE RESP [FILTEROFF]
 ##     function that executes JQCODE on RESP string
 ##     if FILTEROFF is populated, will parse responses without "valid": true
 ##     calls `jq -r "JQCODE" <<<"RESP"` and prints result
-##   __gs_check_version RESP
+##   __gs_check_resp RESP
 ##     parses json RESP string for oldver key found when server api version is old
-##     prints warning and returns 1 if version is old
-##     server will not comply with requests if version is old
+##       or oldkey key found when server api key is bad
+##     prints warning and returns 1 if either is old
+##     server will not comply with requests if client out of compliance with key/version
 ##   __gs_response_valid RESP
 ##     checks json RESP string for '"valid": true'
-##     server should include valid bool flag in every response
+##     server should include valid bool flag in every response except in the /user route
 ##     returns 1 if valid is missing or not true
 ##   __gs_request REQ [OPTS]
-##     function to handle common game requests/responses
+##     function to handle common game request/response routes
 ##     supported REQ values and their OPTS:
-##       _apikey_: gets api key from server if able
+##       _apikey_ [CREATE]: gets api key from server if able
+##                          creates user if CREATE is populated
 ##       _login_ PASSWD: logs in to server and handles possible errors
 ##                       allows users to set password on first login
 ##
 ## Author: Daniel Tucker <github.com/Vision940>
 ##
 
-__gs_json_content() {
-  local arg
-  local jsonContent=""
-
-  if (( $# % 2 == 1 )); then
-    return 1
-  fi
-
-  for (( arg=1 ; arg<=$# ; arg++ )); do
-    if (( arg % 2 == 1 )); then
-      jsonContent+="\"${!arg}\": "
-    else
-      jsonContent+="\"${!arg}\", "
-    fi
-  done
-  echo "${jsonContent%, }"
+__gs_logged_in() {
+  [[ -n "$GS_API_KEY" && "$GS_USER_STATE" == "Loggedin" ]]
 }
 
-# __gs_curl_post ROUTE [KEY VAL [KEY VAL [...]]]
+__gs_api_key() {
+  local action="$1"
+  __gs_required_args action || return 2
+  case _${action}_ in
+    _save_)
+      local key="$2"
+      __gs_required_args key || return 2
+      __gs_required_args -n GS_AUTH_FILE || return 1
+
+      export GS_API_KEY="$key"
+
+      command rm -f "$GS_AUTH_FILE" 2>/dev/null
+      command echo -n "$key" > "$GS_AUTH_FILE" 2>/dev/null
+      command chmod 600 "$GS_AUTH_FILE" 2>/dev/null
+
+      [[ "$(command cat "$GS_AUTH_FILE" 2>/dev/null)" == "$key" ]]
+      return
+    ;;
+    _remove_)
+      __gs_unset_vars_from_prefixes GS_API_KEY GS_USER_STATE
+      [[ -f "$GS_AUTH_FILE" ]] && command rm -f "$GS_AUTH_FILE" 2>/dev/null
+    ;;
+  esac
+}
+
+__gs_json_content() {
+  (( $# % 2 == 1 )) && return 1
+
+  local args=()
+
+  local key val json
+  while (($#)); do
+    key=$1
+    val=$2
+    shift 2
+
+    json=""
+    [[ "$val" =~ ^"{" ]] && json="json"
+    [[ " false true " =~ " $val " ]] && json="json"
+
+    args+=("--arg$json" "$key" "$val")
+  done
+
+  jq -cn "${args[@]}" '$ARGS.named'
+}
+
 __gs_curl_post() {
   local route="$1"
-  local jsonContent=""
 
-  jsonContent="$(__gs_json_content ${@:2})" || return 1
-  # Add these to all messages
-  jsonContent+="${jsonContent:+, }\"user\": \"$GS_USER\", \"key\": \"$GS_API_KEY\", \"ver\": \"$GS_SERVER_API_VER\""
+  # Don't let users trick login before setting password
+  [[ "${GS_API_KEY^^}" == "NULL" ]] && unset GS_API_KEY
 
-  __gs_debugmsg "Requesting $GS_URL/$route with {$jsonContent}" 2
-  __gs_debugmsg "curl -L -m 5 -X POST -H \"Content-Type: application/json\" -d \"{${jsonContent//\"/\\\"}}\" $GS_URL/$route" 3
-  local response=$(curl -sL -m 5 -X POST -H "Content-Type: application/json" -d "{$jsonContent}" $GS_URL/$route)
-  __gs_debugmsg "resp: $response" 2
-  __gs_check_version "$response"
+  # Populate json with defaults and opts
+  local json="$(
+    __gs_json_content "${@:2}" \
+      user "$GS_USER" \
+      curuser "$GS_CURUSER" \
+      host "${HOSTNAME:-$(hostname 2>/dev/null || command cat /etc/hostname 2>/dev/null || echo unknown)}" \
+      key "${GS_API_KEY:-}" \
+      ver "$GS_SERVER_API_VER"
+  )" || return 1
+
+  __gs_debugmsg "Requesting $GS_URL/$route with $json" 5
+
+  local response
+  response=$(
+    curl -sL -m 2 \
+      -X POST \
+      -H "Content-Type: application/json" \
+      -d "$json" \
+      "$GS_URL/$route"
+  ) || return 1
+
+  __gs_debugmsg "resp: $response" 6
+  __gs_check_resp "$response" || return 1
   printf "%s" "$response"
 }
 
-# __gs_parse_response JQCODE RESP [FILTEROFF]
 __gs_parse_response() {
   local keyStr="$1"
   local jsonResp="$2"
@@ -81,52 +138,130 @@ __gs_parse_response() {
   fi
 }
 
-__gs_check_version() {
+__gs_check_resp() {
   local jsonResp="$1"
+
   if jq -e ".oldver == true" <<<"$jsonResp" &>/dev/null; then
-    __gs_errormsg "Old server api version detected."
+    __gs_errormsg "Old server API version detected."
     __gs_errormsg "Please run \`game update\` to get the latest server updates!"
+    return 1
+  fi
+
+  if jq -e ".oldkey == true" <<<"$jsonResp" &>/dev/null; then
+    __gs_errormsg "Invalid server API key."
+    __gs_errormsg "Please run \`game login\` to re-authenticate."
     return 1
   fi
 }
 
 __gs_response_valid() {
   local jsonResp="$1"
-  jq -e ".valid == true" <<<"$jsonResp" &>/dev/null && return 0
-  return 1
+  jq -e ".valid == true" <<<"$jsonResp" &>/dev/null
 }
 
 __gs_request() {
   __gs_debugmsg "Attempting to send $1 request"
+
   case _$1_ in
     __apikey__)
-      local response=$(__gs_curl_post user)
-      __gs_parse_response ".key" "$response"
+      local create="${2:+true}"
+      local response
+      response=$(__gs_curl_post user create "${create:-false}") || return 1
+      local key=$(__gs_parse_response ".key // null" "$response" off)
+      local action=$(__gs_parse_response ".action // null" "$response" off)
+
+      if [[ "$key" != "null" ]]; then
+        export GS_USER_STATE=Loggedin
+        __gs_api_key save "$key" || __gs_debugmsg "Could not save api key for $GS_USER"
+        return 0
+      fi
+
+      __gs_api_key remove
+
+      [[ "action" == "null" ]] && {
+        __gs_debugmsg "API key not returned and action is null"
+        return 1
+      }
+
+      export GS_USER_STATE="${action// }"
+      case $GS_USER_STATE in
+        Usernameinvalid)
+          __gs_errormsg "Invalid username \"$GS_USER\"" fatal
+          return 1
+        ;;
+        Userdisavowed)
+          __gs_errormsg "User \"$GS_USER\" has been banned or rejected" fatal
+          return 1
+        ;;
+        Userexists)
+          __gs_debugmsg "User \"$GS_USER\" already exists"
+        ;;
+        Usernotcreated)
+          __gs_debugmsg "User \"$GS_USER\" does not exist and was not created"
+        ;;
+        Userrequested)
+          __gs_debugmsg "User \"$GS_USER\" does not exist and was requested"
+        ;;
+        Userpending)
+          __gs_debugmsg "User \"$GS_USER\" has not yet been approved"
+        ;;
+        Login)
+          __gs_debugmsg "User \"$GS_USER\" requires login"
+        ;;
+        Setpassword)
+          __gs_debugmsg "User \"$GS_USER\" needs to set a password"
+        ;;
+      esac
     ;;
     __login__)
-      local response=$(__gs_curl_post login password $2) || return 1
+      # Handle user states from _apikey_ call
+      case $GS_USER_STATE in
+        Setpassword)
+          __gs_set_passwd $2
+          return
+        ;;
+        Userrequested|Userpending)
+          __gs_infomsg "Please wait to log in until approved."
+          return 1
+        ;;
+      esac
+
+      local response
+      response=$(__gs_curl_post login password $2) || return 1
+
       if __gs_response_valid "$response"; then
-        GS_API_KEY=$(__gs_parse_response ".key" "$response") || return 1
+        export GS_USER_STATE=Loggedin
+        local key
+        key=$(__gs_parse_response ".key" "$response") || return 1
+        __gs_api_key save "$key" || __gs_debugmsg "Could not save api key for $GS_USER"
+
         __gs_infomsg "Successfully logged in $GS_USER!"
         return 0
-      else
-        local action=$(__gs_parse_response ".action" "$response" off) || return 1
-        __gs_debugmsg "Action needed: $action"
-        case "${action// /}" in
-          Setpassword)
-            __gs_set_passwd $2 || return 1
-          ;;
-          Retrypassword)
-            __gs_errormsg "Incorrect password to login. Please try again or ask an administrator to reset it."
-          ;;
-          Invaliduser)
-            # Should hopefully never get here
-            __gs_errormsg "User $GS_USER is not a user on the server. Please contact an administrator for assistance." fatal
-          ;;
-        esac
-
-        return 1
       fi
+
+      local action
+      action=$(__gs_parse_response ".action" "$response" off) || return 1
+      __gs_debugmsg "Action needed: $action"
+
+      GS_USER_STATE="${action// }"
+      case $GS_USER_STATE in
+        Retrypassword)
+          #TODO: Admin password reset
+          __gs_errormsg "Incorrect password to login. Please try again or ask an administrator to reset it."
+        ;;
+        Invaliduser)
+          # Should hopefully never get here
+          __gs_errormsg "User \"$GS_USER\" is not a user on the server. Please contact an administrator for assistance." fatal
+        ;;
+        Userdisavowed)
+          __gs_errormsg "User \"$GS_USER\" has been banned or rejected" fatal
+          __gs_nuke_client
+        ;;
+        Userpending)
+          __gs_infomsg "Please wait until approved."
+        ;;
+      esac
+      return 1
     ;;
   esac
 }
diff --git a/static/client/game b/static/client/game
--- a/static/client/game
+++ b/static/client/game
@@ -34,6 +34,7 @@ done
 unset import __GS_IMPORTS
 
 game() {
+  __gs_longopts "$@" && return
   __gs_setdebug $1 || shift
 
   if [[ "${GS_API_KEY:-null}" == "null" && "$1" != "login" ]]; then
@@ -46,19 +47,34 @@ game() {
     # User-facing functionality
     #TODO: Add load (and a game to load!)
     _login_) : Log into the server
-      [[ -n "$GS_API_KEY" ]] && {
-        __gs_errormsg "You are already logged in";
+      __gs_infomsg "Logging in $GS_USER..."
+      __gs_infomsg "To change users, run \`gameinit -u USERNAME\`"
+
+      # Check if user is already logged in
+      __gs_logged_in && {
+        __gs_errormsg "$GS_USER is already logged in";
         __gs_errormsg "Run \`${FUNCNAME[-1]} logout\` to log out."
-        return;
+        return
       }
+
+      # Try to refresh api key if client is out of date
+      __gs_request _apikey_ || return 1
+      __gs_logged_in && {
+        __gs_infomsg "Successfully logged in $GS_USER!"
+        return 0
+      }
+
       __gs_source_file functions/userctl || return 1
 
+      # Get password
       local hashedPassword
       hashedPassword=$(__gs_passwd_prompt) || { __gs_userctl_cleanup; return 1; }
       echo
 
-      __gs_request _login_ $hashedPassword || { __gs_userctl_cleanup; return 1; }
+      # Login with password
+      __gs_request _login_ "$hashedPassword" || { __gs_userctl_cleanup; return 1; }
 
+      # Cleanup
       __gs_userctl_cleanup
     ;;
     _passwd_) : Change server password
@@ -71,7 +87,7 @@ game() {
       echo
 
       __gs_request _login_ $hashedPassword || { __gs_userctl_cleanup; return 1; }
-      if [[ -n "$GS_API_KEY" ]]; then
+      if __gs_logged_in; then
         hashedPassword=$(__gs_passwd_prompt new) || { __gs_userctl_cleanup; return 1; }
         echo
         __gs_set_passwd $hashedPassword || { __gs_userctl_cleanup; return 1; }
@@ -82,8 +98,7 @@ game() {
       __gs_userctl_cleanup
     ;;
     _logout_) : Log out of the server
-      # It's kind of dumb to make this an option but it could also make sense later
-      unset GS_API_KEY
+      __gs_api_key remove
       __gs_infomsg "Successfully logged out $GS_USER!"
     ;;
     _update_) : Get latest version of game
diff --git a/templates/client/init b/templates/client/init
--- a/templates/client/init
+++ b/templates/client/init
@@ -3,10 +3,13 @@
 ## templates/client/init ##
 ## Script to init a client to the gameserver
 ##
-## Exports necessary env vars, checks for external deps, and sources game cmd
+## Exports necessary env vars, checks for external deps, and sets up gameinit cmd
 ##
 ## Users access server capabilities with this script by running:
-##   source <(curl -sfL http://<hostname>:<port>/)
+##   source <(curl -sfL SERVER-URL)
+##   gameinit OPTS
+## Alternatively, users can run gameinit on source like so:
+##   source <(curl -sfL SERVER-URL) OPTS
 ##
 ## Functions:
 ##   __gs_source_file PATH ROUTE
@@ -14,6 +17,12 @@
 ##     default ROUTE is static/client
 ##   __gs_deps_check
 ##     function that runs one time on init source to check gameserver dependencies
+##   gameinit
+##     function to source game command after init script sourced
+##     automatically runs on source if $@ is populated
+##     functionizing game command init is beneficial because it:
+##       adds layer of confirmation from new users sourcing this script
+##       allows retry of init if init fails for whatever reason or if opts wrong
 ##
 ## Author: Daniel Tucker <github.com/Vision940>
 ##
@@ -59,22 +68,116 @@ __gs_deps_check() {
     fi
   done
 }
-__gs_deps_check || return
+__gs_deps_check || return 1
 
+# These are set from server config
 export GS_HOST="{{ host }}"
 export GS_PORT="{{ port }}"
-export GS_URL="http://$GS_HOST:$GS_PORT"
 export GS_SERVER_API_VER="{{ server_ver }}"
+export GS_URL="http://$GS_HOST:$GS_PORT"
 
-# __gs_source_file PATH ROUTE
+# These dir variables are available to games that want persistent data state
+#   across client sessions in source location
+# Games should not expect these directories to house important information,
+#   as users can log in from different homes/machines/usernames
+export GS_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME:-/tmp}/.config}/gameserver"
+export GS_DATA_DIR="${XDG_DATA_HOME:-${HOME:-/tmp}/.local/share}/gameserver"
+export GS_AUTH_FILE="$GS_DATA_DIR/auth.txt"
+
 __gs_source_file() {
   local serverPath=${2:-static/client}
   declare -f __gs_debugmsg &>/dev/null && __gs_debugmsg "Sourcing $1..."
-  source <(curl -sfL "$GS_URL/$serverPath/$1")
+  source <(curl -sfL "$GS_URL/$serverPath/$1") || {
+    declare -f __gs_debugmsg &>/dev/null && __gs_debugmsg "Could not source $1"
+    return 1
+  }
 }
 
-# Prioritize id and whoami to avoid impersonation
-export GS_USER=$(id -u -n 2>/dev/null || whoami 2>/dev/null || echo $USER)
-__gs_source_file game
-export GS_API_KEY=$(__gs_request _apikey_)
+gameinit() {
+  __gs_source_file functions/docs
+  __gs_longopts "$@" && return
+
+  # Prioritize id and whoami to avoid impersonation
+  export GS_CURUSER=$(id -u -n 2>/dev/null || whoami 2>/dev/null || echo $USER)
+
+  local create=
+  export GS_USER=$GS_CURUSER
+  local opt OPTIND OPTARG
+  while getopts 'cu:' opt; do
+    case "$opt" in
+      c) create=true ;;
+      u) GS_USER=$OPTARG ;;
+      *) __gs_errormsg "Unrecognized option to $FUNCNAME"; return 2 ;;
+    esac
+  done
+  shift $(( OPTIND - 1 ))
+
+  # Create data/config dirs
+  for dir in "$GS_CONFIG_DIR" "$GS_DATA_DIR"; do
+    command mkdir -m 755 -p "$dir" &>/dev/null || {
+      echo -e "gameserver: [\033[31;1mFATAL ERROR\033[0m] Could not create directory at $dir." 1>&2
+      return 1
+    }
+    [[ -d "$dir" ]] || {
+      echo -e "gameserver: [\033[31;1mFATAL ERROR\033[0m] Location $dir is not a directory." 1>&2
+      return 1
+    }
+  done
+
+  # Source game command
+  __gs_source_file game || {
+    echo -e "gameserver: [\033[31;1mFATAL ERROR\033[0m] Could not source game command." 1>&2
+    return 1
+  }
+
+  # Load cached key if it exists
+  [[ -r "$GS_AUTH_FILE" ]] && export GS_API_KEY="$(<$GS_AUTH_FILE)"
+
+  # Get user state and set key if able
+  __gs_request _apikey_ $create || {
+    # If api key get fails with return code, user is either banned or invalid
+    # In this case, erase all trace of existence
+    __gs_errormsg "Unrecoverable error on startup" fatal
+    __gs_nuke_client
+    return 1
+  }
+
+  [[ "${FUNCNAME[-1]}" == "gameinit" ]] || return 0
+
+  # Print user state hints if run directly
+  case $GS_USER_STATE in
+    Usernotcreated)
+      __gs_warnmsg "User \"$GS_USER\" does not exist."
+      __gs_warnmsg "Run \`$FUNCNAME -c [-u USERNAME=$GS_CURUSER]\` to create!"
+      unset -f game
+    ;;
+    Userexists)
+      __gs_errormsg "User \"$GS_USER\" already exists."
+      __gs_errormsg "Run without \`-c\` or with a different username to continue!"
+      unset -f game
+    ;;
+    Userrequested)
+      __gs_infomsg "User \"$GS_USER\" has been requested."
+      __gs_infomsg "Check back here with \`$FUNCNAME [-u USERNAME=$GS_CURUSER]\` for approval status!"
+    ;;
+    Userpending)
+      __gs_infomsg "User \"$GS_USER\" has not yet been approved."
+      __gs_infomsg "Contact an admin ({{ admins | join(', ') }}) if it's been a while."
+    ;;
+    Login)
+      __gs_warnmsg "User \"$GS_USER\" requires login."
+    ;;
+    Setpassword)
+      __gs_infomsg "User \"$GS_USER\" has been approved."
+      __gs_infomsg "Run \`game login\` to set a password!"
+    ;;
+  esac
+
+  return 0
+}
+
+(($#)) && {
+  gameinit "$@" || return 1
+}
+return 0
 
