Implement popup pause menu for demo game
Implement floating point math with bash builtins

Add unit test for math functions

Add unit test runs to make

Set term size globals on startup

Create default key->event binds and provide method to add/change/restore

Add "scenes" that can stack and change what is rendered per frame

Start on demo game with simple example scenes all games can use

Make event system scene-specific

Add node system for game scene components

Add basic widget node types for scenes to use

Buffer mouse move input to keep up with overwhelming data amount

Add button manager container widget to handle all buttons in any given
scene/context

Reorganize game files such that one game has one directory with all
files

Add default config and sprite path for eventual easy demo game creation

Add frame draw/render logic for sprite cells in terminal grid

Remove .spr files from git with eye to generate/package them in release only

Support transparent cells in sprites

Add functional dynamic popup menu widget for displaying menus

Refactor some of base-game to support eventual boom online
implementation

diff --git a/static/client/functions/utility b/static/client/functions/utility
--- a/static/client/functions/utility
+++ b/static/client/functions/utility
@@ -4,13 +4,18 @@
 ## Provides utility functions for other functions
 ##
 ## Functions:
-##   __gs_required_args [-nd] [ARG ARG ...]
+##   __gs_required_args [-ndvq] [ARG ARG ...]
 ##     function to check if ARG names are set in env
 ##     opts:
 ##       -n  ARG is an env var that should be set
 ##       -d  just print as debug if ARG unset
+##       -v  just check if var exists with `declare -p`
+##       -q  don't log non-existence
 ##     otherwise, prints error saying required arg ARG not set in fxn
 ##     returns non-zero on first ARG unset
+##   __gs_required_fxn FXN-NAME
+##     checks for function FXN-NAME in env and returns non-zero with
+##       error msg if missing
 ##   __gs_trap_check SIGNAL
 ##     function to check if SIGNAL is a trap in the current env
 ##     returns non-zero if SIGNAL is trapped
@@ -19,32 +24,56 @@
 ##     returns 0 if >= VERSION
 ##     this is here as a preliminary check to avoid weird term states
 ##     still expect to catch misisng newer bash features with ||
+##   __gs_unset_vars_from_prefixes PREFIX [PREFIX ...]
+##     find all vars in env starting with each PREFIX and unset them all
+##     useful to clean up env after function runs
 ##
 ## Author: Daniel Tucker <github.com/Vision940>
 ##
 
 __gs_required_args() {
   local isArg=true
+  local vague=false
   local logger=__gs_errormsg
   local opt OPTIND OPTARG
-  while getopts 'nd' opt; do
+  while getopts 'ndvq' opt; do
     case "$opt" in
-      d) logger=__gs_debugmsg;;
-      n) isArg=false;;
-      *) __gs_errormsg "Unrecognized option to required args"; return 2;;
+      d) logger=__gs_debugmsg ;;
+      n) isArg=false ;;
+      v) vague=true ;;
+      q) logger=: ;;
+      *) __gs_errormsg "Unrecognized option to required args"; return 2 ;;
     esac
   done
   shift $(( OPTIND - 1 ))
 
   local arg
   for arg in $@; do
-    __gs_debugmsg "Checking $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]} has value - \"${!arg}\"" 3
-    [[ -z "${!arg}" ]] && {
-      $logger "Missing $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]}"
-      return 2
-    }
+    if $vague; then
+      __gs_debugmsg "Checking $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]} is declared" 4
+      declare -p $arg &>/dev/null || {
+        $logger "Missing $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]}"
+        return 1
+      }
+    else
+      __gs_debugmsg "Checking $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]} has value - \"${!arg}\"" 4
+      [[ -z "${!arg}" ]] && {
+        $logger "Missing $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]}"
+        return 2
+      }
+    fi
   done
 
+  return 0
+}
+
+__gs_required_fxn() {
+  local fxnName="$1"
+  __gs_required_args fxnName || return 2
+  declare -f "$fxnName" &>/dev/null || {
+    __gs_errormsg "Missing $fxnName function required to ${FUNCNAME[1]}"
+    return 1
+  }
   return 0
 }
 
@@ -74,4 +103,17 @@ __gs_bash_ver_check() {
   # Return 0 if >= version passed in
   (( BASH_VERSINFO[0] > $major || (BASH_VERSINFO[0] == $major && BASH_VERSINFO[1] >= $minor) ))
 }
+
+__gs_unset_vars_from_prefixes() {
+  (($#)) || return 2
+
+  local prefix name
+  for prefix in $@; do
+    while IFS= read -r name; do
+      unset "$name"
+    done < <(compgen -v "$prefix")
+  done
+}
+
+#TODO: Unset funcs from prefixes
 
diff --git a/templates/engine/game-common b/templates/engine/game-common
--- a/templates/engine/game-common
+++ b/templates/engine/game-common
@@ -11,12 +11,13 @@
 ## Functions:
 ##   __gs_GAME_common (init|deinit) - easy function to init/deinit a game
 ##                                    provides one fxn call for game setup/teardown
-##   __gs_GAME_exit PARENT - defined if __gs_GAME_exit is undefined in static/games/GAME
-##                           runs `__gs_GAME_common deinit` and is used by term trap
 ##
 ## Configurable elements to __gs_GAME_common:
 ##   mouse: games can add "mouse: true" to their cfg to optionally enable mouse
 ##            input while inited
+##
+## This sources a default demo game (templates/engine/game-demo) to enable games
+##   being playable in a demo example state after just a directory being created
 ##
 ## Author: Daniel Tucker <github.com/Vision940>
 ##
@@ -26,11 +27,8 @@ __gs_source_common() {
   unset -f $FUNCNAME
 
   local __GS_COMMON=(
-    games/{{ game.cmd_name }}-utils
-    static/engine/cache
-    static/engine/streams
-    static/engine/input
-    static/engine/term
+    games/{{ game.source_name }}-utils
+    static/engine/{graphics,cache,streams,input,events,term,nodes,scenes}
   )
 
   local import
@@ -46,47 +44,55 @@ __gs_{{ game.cmd_name }}_common() {
 
   case _${action}_ in
     _init_)
+      # Get game name and exit tracker into environment
+      GS_GAME={{ game.cmd_name }}
+      GS_EXIT=false
       # Cache init is first because sprites and term need it
       __gs_cache init {{ game.cmd_name }} || return 1
       # Load sprites to cache dir for game
       __gs_cache load-sprites {{ game.cmd_name }} || return 1
       # Init term for game
       __gs_{{ game.cmd_name }}_term init || return 1
-      # Get event handler fd
-      __gs_stream create {{ game.cmd_name }}_events || return 1
+      # Set up term env variables for game
+      __gs_{{ game.cmd_name }}_term env || return 1
       # Init keyboard handler
       __gs_keyboard init || return 1
       {% if game.mouse %}
       # Init mouse handler after keyboard
       __gs_mouse init || return 1
       {% endif %}
+      # Set up event env
+      __gs_event setup
+      # Set up scene env
+      __gs_scene_manager setup
+      # Set up node/widget envs
+      __gs_node_manager setup
+      # Set up frame env
+      __gs_frame setup
     ;;
     _deinit_)
+      # Remove game name and exit tracker from env
+      unset GS_GAME GS_EXIT
       # __gs_GAME_term's RETURN trap runs __gs_term deinit so that is omitted here
-      # Destroy event handler stream
-      __gs_stream destroy {{ game.cmd_name }}_events
-      {% if game.mouse %}
-      # Close mouse handler before keyboard
-      __gs_mouse deinit
-      {% endif %}
+      # __gs_term deinit deinits mouse, so that is also omitted
       # Close keyboard handler - must be before deinit cache
       __gs_keyboard deinit-stream
       # Remove entire game cache
       __gs_cache deinit
+      # Clean up event env
+      __gs_event cleanup
+      # Clean up scene env
+      __gs_scene_manager cleanup
+      # Clean up node env
+      __gs_node_manager cleanup
+      # Clean up frame env
+      __gs_frame cleanup
+      #TODO: Unset game-specific funcs from prefixes
       # Untrap keyboard ^C trap as final action
       __gs_keyboard deinit-trap
     ;;
   esac
 }
 
-# Define default exit function if __gs_GAME_exit undefined
-if ! declare -f __gs_{{ game.cmd_name }}_exit &>/dev/null; then
-  __gs_{{ game.cmd_name }}_exit() {
-    # Only run if return of $1 function
-    [[ "${FUNCNAME[1]}" == "$1" ]] || return 1
-
-    __gs_{{ game.cmd_name }}_common deinit
-    return 0
-  }
-fi
+__gs_source_games {{ game.source_name }}-demo
 
