Migrate server to use database
Updated user, login, and passwd routes

Updated client init script and messenger

Add db.py for database operations/pool management

Add 001_users.sql migration to create user tables

Clean up / improve most python import modules

Add migrate.py to run db schema migrations on install/update

Add dev-install.py and dev/devserver scripts to run local dev server

Add support for --help/--version in user-facing commands

Add `game admin` command that has different functions depending on role

Add admin request handling and game users command with varying levels
of detail in response

Add list_users, cancel, and whoami routes to server

Add admin ban handling and game account command

Add prompts functions for capturing user input in the command line

This sets up server much better for user handling / game data in the
long run

diff --git a/static/client/game b/static/client/game
--- a/static/client/game
+++ b/static/client/game
@@ -25,7 +25,7 @@
 __GS_IMPORTS=(
   sources/cmdenv/cmdenv
   sources/tput/tput
-  functions/{docs,fetcher,math,messenger,logging,utility}
+  functions/{docs,fetcher,logging,math,messenger,output,prompts,utility}
 )
 
 for import in ${__GS_IMPORTS[@]}; do
@@ -33,7 +33,11 @@ for import in ${__GS_IMPORTS[@]}; do
 done
 unset import __GS_IMPORTS
 
+# Curl admin route for appropriate __gs_admin function
+source <(__gs_curl_post -q admin) || __gs_debugmsg "Admin template failed on source"
+
 game() {
+  __gs_longopts "$@" && return
   __gs_setdebug $1 || shift
 
   if [[ "${GS_API_KEY:-null}" == "null" && "$1" != "login" ]]; then
@@ -42,23 +46,53 @@ game() {
     return 1
   fi
 
+  local resp
   case _$1_ in
     # User-facing functionality
     #TODO: Add load (and a game to load!)
+    _account_) : View account info
+      resp=$(__gs_curl_post whoami) || return 1
+      __gs_json_to_table \
+        -d "user_profile" \
+        -j "$resp" \
+        Username:username Status:status "Last Seen:last_seen_at"
+    ;;
+    _admin_) : View admin info
+      __gs_required_fxns __gs_admin || return 1
+      __gs_admin "${@:2}"
+    ;;
     _login_) : Log into the server
-      [[ -n "$GS_API_KEY" ]] && {
-        __gs_errormsg "You are already logged in";
+      __gs_infomsg "Logging in $GS_USER..."
+      __gs_infomsg "To change users, run \`gameinit -u USERNAME\`"
+
+      # Check if user is already logged in
+      __gs_logged_in && {
+        __gs_errormsg "$GS_USER is already logged in";
         __gs_errormsg "Run \`${FUNCNAME[-1]} logout\` to log out."
-        return;
+        return
       }
+
+      # Try to refresh api key if client is out of date
+      __gs_request _apikey_ || return 1
+      __gs_logged_in && {
+        __gs_infomsg "Successfully logged in $GS_USER!"
+        return 0
+      }
+
       __gs_source_file functions/userctl || return 1
 
+      # Get password
       local hashedPassword
       hashedPassword=$(__gs_passwd_prompt) || { __gs_userctl_cleanup; return 1; }
       echo
 
-      __gs_request _login_ $hashedPassword || { __gs_userctl_cleanup; return 1; }
+      # Login with password
+      __gs_request _login_ "$hashedPassword" || { __gs_userctl_cleanup; return 1; }
 
+      # Grab correct __gs_admin function
+      source <(__gs_curl_post -q admin)
+
+      # Cleanup
       __gs_userctl_cleanup
     ;;
     _passwd_) : Change server password
@@ -71,7 +105,7 @@ game() {
       echo
 
       __gs_request _login_ $hashedPassword || { __gs_userctl_cleanup; return 1; }
-      if [[ -n "$GS_API_KEY" ]]; then
+      if __gs_logged_in; then
         hashedPassword=$(__gs_passwd_prompt new) || { __gs_userctl_cleanup; return 1; }
         echo
         __gs_set_passwd $hashedPassword || { __gs_userctl_cleanup; return 1; }
@@ -82,8 +116,7 @@ game() {
       __gs_userctl_cleanup
     ;;
     _logout_) : Log out of the server
-      # It's kind of dumb to make this an option but it could also make sense later
-      unset GS_API_KEY
+      __gs_api_key remove
       __gs_infomsg "Successfully logged out $GS_USER!"
     ;;
     _update_) : Get latest version of game
@@ -97,16 +130,27 @@ game() {
         __gs_warnmsg "No new changes detected."
       fi
     ;;
+    _users_) : See user info
+      resp=$(__gs_curl_post list_users) || return 1
+      if jq -e ".admin == true" <<<"$resp" &>/dev/null; then
+        __gs_json_to_table \
+          -d "users" -a \
+          -j "$resp" \
+          ID:id Username:username Status:status "Status By:status_by" \
+          "Status Reason:status_reason" "Status Time:status_at" \
+          "Last Seen:last_seen_at"
+      else
+        __gs_json_to_table \
+          -d "users" -a \
+          -j "$resp" \
+          Username:username Status:status "Last Seen:last_seen_at"
+      fi
+    ;;
     _help_) : Open game help
       __gs_doccer
     ;;
-    __)
-      __gs_infomsg "Run \`${FUNCNAME[-1]} help\` for help!"
-    ;;
-    *)
-      __gs_errormsg "Option $1 not found."
-      __gs_infomsg "Run \`${FUNCNAME[-1]} help\` for help!"
-    ;;
+    __) __gs_unfound_option ;;
+    *) __gs_unfound_option "$1" ;;
   esac
 }
 __gs_source_template game-completion
